# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='dt',
            new_name='date_time',
        ),
    ]
