# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20171126_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ManyToManyField(to='notes.Category'),
        ),
    ]
