# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
